# Generated by Django 4.2.3 on 2023-12-06 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '__first__'),
        ('work_space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('sources', models.ManyToManyField(related_name='sources', to='bookshelf.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='work_space.workspace')),
            ],
        ),
    ]
