# Generated by Django 4.2.3 on 2023-10-23 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paper_work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(upload_to=paper_work.models.user_directory_path)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_work.paper')),
            ],
        ),
    ]
