# Generated by Django 4.2.3 on 2024-02-20 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('citation_style', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA')], max_length=3)),
                ('archived', models.BooleanField(default=False)),
                ('sources', models.ManyToManyField(related_name='papers', to='bookshelf.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='work_space.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apa', models.TextField(blank=True)),
                ('mla', models.TextField(blank=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibliography', to='paper_work.paper')),
            ],
        ),
    ]
