# Generated by Django 4.2.3 on 2023-12-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='is_archived',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='is_finished',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='is_published',
            new_name='published',
        ),
    ]
