# Generated by Django 4.2.3 on 2023-10-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
        ('paper_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='work_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='work_space.workspace'),
            preserve_default=False,
        ),
    ]
