# Generated by Django 4.2.3 on 2023-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_endnote_source'),
        ('paper_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='sources',
            field=models.ManyToManyField(related_name='sources', to='bookshelf.source'),
        ),
    ]
