# Generated by Django 4.2.3 on 2023-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0025_alter_webpage_page_url'),
        ('paper_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='sources', to='bookshelf.source'),
        ),
    ]
