# Generated by Django 4.2.3 on 2023-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
        ('paper_work', '0002_rename_is_archived_paper_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='finished',
        ),
        migrations.AlterField(
            model_name='paper',
            name='sources',
            field=models.ManyToManyField(related_name='papers', to='bookshelf.source'),
        ),
    ]
