# Generated by Django 4.2.3 on 2023-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0002_paper_work_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
