# Generated by Django 4.2.3 on 2023-10-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_workspace_is_archived'),
        ('paper_work', '0002_paper_work_space_delete_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='work_space.workspace'),
        ),
    ]
