# Generated by Django 4.2.3 on 2023-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0003_remove_paper_finished_alter_paper_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
