# Generated by Django 4.2.3 on 2023-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0003_paperversion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperversion',
            name='paper_title',
            field=models.CharField(default='sd', max_length=50),
            preserve_default=False,
        ),
    ]
