# Generated by Django 4.2.3 on 2024-02-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0004_alter_paper_citation_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='citation_style',
        ),
    ]
