# Generated by Django 4.2.3 on 2023-12-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0004_paper_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='finished',
        ),
    ]
