# Generated by Django 4.2.3 on 2023-10-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0004_paperversion_paper_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperversion',
            old_name='text',
            new_name='file',
        ),
    ]
