# Generated by Django 4.2.3 on 2024-02-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0005_remove_paper_citation_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibliography', to='paper_work.paper')),
            ],
        ),
    ]
