# Generated by Django 4.2.3 on 2023-10-24 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0005_rename_text_paperversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperversion',
            name='saving_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
