# Generated by Django 4.2.3 on 2023-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0005_remove_paper_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation_style',
            field=models.CharField(default='APA & MLA', max_length=10),
        ),
    ]
