# Generated by Django 4.2.3 on 2024-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0006_bibliography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliography',
            old_name='text',
            new_name='apa',
        ),
        migrations.AddField(
            model_name='bibliography',
            name='mla',
            field=models.TextField(default='dd'),
            preserve_default=False,
        ),
    ]
