# Generated by Django 4.2.3 on 2023-10-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0006_paperversion_saving_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperversion',
            name='paper_title',
        ),
    ]
