# Generated by Django 4.2.3 on 2024-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0007_rename_text_bibliography_apa_bibliography_mla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='apa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='mla',
            field=models.TextField(blank=True),
        ),
    ]
