# Generated by Django 4.2.3 on 2023-10-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_work', '0007_remove_paperversion_paper_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperversion',
            name='user',
        ),
    ]
