# Generated by Django 4.2.3 on 2023-12-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_page_is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
