# Generated by Django 4.2.3 on 2023-12-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_page_is_opened',
        ),
    ]
