# Generated by Django 4.2.3 on 2024-02-20 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_handling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_work', '__first__'),
        ('bookshelf', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_extension', models.CharField(max_length=4)),
                ('file', models.FileField(blank=True, upload_to=file_handling.models.source_saving_path)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='bookshelf.source')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_text', models.CharField(blank=True, max_length=100)),
                ('version_number', models.CharField(max_length=50)),
                ('file_extension', models.CharField(max_length=4)),
                ('uploading_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=file_handling.models.paper_saving_path)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='paper_work.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
