# Generated by Django 4.2.3 on 2024-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfile',
            name='commit_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
