# Generated by Django 4.2.3 on 2024-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0002_paperfile_commit_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperfile',
            name='saving_time',
        ),
        migrations.AddField(
            model_name='paperfile',
            name='version_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
