# Generated by Django 4.2.3 on 2024-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0003_remove_paperfile_saving_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperfile',
            name='version_number',
            field=models.CharField(max_length=50),
        ),
    ]
