# Generated by Django 4.2.3 on 2024-02-18 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0005_paperfile_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfile',
            name='uploading_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
