# Generated by Django 4.2.3 on 2023-12-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space_parts', '0002_comment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='added',
        ),
    ]
