# Generated by Django 4.2.3 on 2023-12-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space_parts', '0003_remove_link_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='My Note', max_length=50),
            preserve_default=False,
        ),
    ]
