# Generated by Django 4.2.3 on 2023-11-07 14:45

import bookshelf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=70)),
                ('multiple_authors', models.BooleanField(default=False)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('file', models.FileField(blank=True, upload_to=bookshelf.models.saving_path)),
                ('link', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source')),
                ('chapter_title', models.CharField(max_length=50)),
                ('chapter_author', models.CharField(max_length=70)),
                ('edition', models.IntegerField(blank=True)),
                ('pages', models.CharField(max_length=20)),
            ],
            bases=('bookshelf.source',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('page', models.IntegerField()),
                ('text', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source')),
                ('has_author', models.BooleanField(default=False)),
                ('website_title', models.CharField(max_length=50)),
                ('page_url', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='work_space.workspace')),
            ],
            bases=('bookshelf.source',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source')),
                ('publishing_house', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='work_space.workspace')),
            ],
            bases=('bookshelf.source',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source')),
                ('journal_title', models.CharField(max_length=50)),
                ('volume_number', models.IntegerField()),
                ('journal_number', models.IntegerField()),
                ('pages', models.CharField(max_length=20)),
                ('is_electronic', models.BooleanField(default=False)),
                ('link_to_journal', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='work_space.workspace')),
            ],
            bases=('bookshelf.source',),
        ),
    ]
