# Generated by Django 4.2.3 on 2024-01-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endnote_apa', models.CharField(max_length=50)),
                ('endnote_mla', models.CharField(max_length=50)),
                ('footnote_apa', models.CharField(max_length=50)),
                ('footnote_mla', models.CharField(max_length=50)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='bookshelf.source')),
            ],
        ),
    ]
