# Generated by Django 4.2.3 on 2024-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='has_file',
            field=models.BooleanField(default=False),
        ),
    ]
