# Generated by Django 4.2.3 on 2023-11-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='real_type',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
