# Generated by Django 4.2.3 on 2023-11-02 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.book')),
                ('pages', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('bookshelf.book',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('link_to_text', models.CharField(blank=True, max_length=40)),
                ('author', models.ManyToManyField(related_name='journals', to='bookshelf.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='work_space.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='link_to_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(default='pinguin', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('journal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.journal')),
                ('pages', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('bookshelf.journal',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('link_to_text', models.CharField(blank=True, max_length=40)),
                ('link', models.CharField(blank=True, max_length=40)),
                ('author', models.ManyToManyField(related_name='websites', to='bookshelf.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='work_space.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='bookshelf.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='bookshelf.author'),
        ),
    ]
