# Generated by Django 4.2.3 on 2023-12-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_endnote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.source'),
        ),
    ]
