# Generated by Django 4.2.3 on 2024-01-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_bibliographicrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliographicrecord',
            name='footnote_apa',
        ),
        migrations.RemoveField(
            model_name='bibliographicrecord',
            name='footnote_mla',
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endnotes', to='bookshelf.source'),
        ),
    ]
