# Generated by Django 4.2.3 on 2023-11-07 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0002_source_real_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
        migrations.RemoveField(
            model_name='website',
            name='work_space',
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='work_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='work_space.workspace'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
