# Generated by Django 4.2.3 on 2023-11-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_author_chapter_journal_book_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
    ]
