# Generated by Django 4.2.3 on 2024-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_source_has_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='page_url',
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, max_length=40),
        ),
    ]
