# Generated by Django 4.2.3 on 2023-11-02 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0002_comment'),
        ('bookshelf', '0003_remove_author_initials_remove_book_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('link_to_text', models.CharField(blank=True, max_length=40)),
                ('publishing_house', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=10)),
                ('authors', models.ManyToManyField(related_name='edited_books', to='bookshelf.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_books', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_books', to='work_space.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleAuthorsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('link_to_text', models.CharField(blank=True, max_length=40)),
                ('publishing_house', models.CharField(max_length=20)),
                ('authors', models.ManyToManyField(related_name='multiple_authors_book', to='bookshelf.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_authors_book', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_authors_book', to='work_space.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book_ptr',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
        migrations.RemoveField(
            model_name='website',
            name='author',
        ),
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
        migrations.RemoveField(
            model_name='website',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.author'),
            preserve_default=False,
        ),
    ]
