# Generated by Django 4.2.3 on 2024-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_webpage_page_url_alter_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
