# Generated by Django 4.2.3 on 2023-11-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_article_user_remove_article_work_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='object_id',
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.source'),
            preserve_default=False,
        ),
    ]
