# Generated by Django 4.2.3 on 2023-11-04 12:17

import bookshelf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_editedbook_multipleauthorsbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedbook',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='editedbook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='editedbook',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='multipleauthorsbook',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='multipleauthorsbook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='multipleauthorsbook',
            name='work_space',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to=bookshelf.models.saving_path),
        ),
        migrations.AddField(
            model_name='book',
            name='multiple_authors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='EditedBook',
        ),
        migrations.DeleteModel(
            name='MultipleAuthorsBook',
        ),
    ]
