# Generated by Django 4.2.3 on 2024-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_source_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
