# Generated by Django 4.2.3 on 2023-11-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_remove_quote_content_type_remove_quote_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='bookshelf.source'),
        ),
    ]
