# Generated by Django 4.2.3 on 2023-11-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_alter_quote_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFromEditedBook',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source')),
                ('chapter_title', models.CharField(max_length=50)),
                ('chapter_author', models.CharField(max_length=70)),
                ('edition', models.IntegerField(blank=True)),
                ('pages', models.CharField(max_length=20)),
            ],
            bases=('bookshelf.source',),
        ),
    ]
