# Generated by Django 4.2.3 on 2023-11-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_remove_book_multiple_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link_to_text',
            new_name='link',
        ),
    ]
