# Generated by Django 4.2.3 on 2023-11-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0001_initial'),
        ('bookshelf', '0006_chapterfromeditedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='work_space.workspace'),
        ),
    ]
