# Generated by Django 4.2.3 on 2023-11-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_alter_source_user_alter_source_work_space'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterFromEditedBook',
            new_name='Chapter',
        ),
    ]
