# Generated by Django 4.2.3 on 2023-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_rename_link_to_text_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
