# Generated by Django 4.2.3 on 2023-11-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_rename_chapterfromeditedbook_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_electronic',
        ),
    ]
