# Generated by Django 4.2.3 on 2023-11-07 11:31

import bookshelf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0002_comment'),
        ('bookshelf', '0009_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=70)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('file', models.FileField(blank=True, upload_to=bookshelf.models.saving_path)),
                ('link', models.CharField(blank=True, max_length=40)),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_electronic', models.BooleanField(default=False)),
                ('link_to_journal', models.CharField(blank=True, max_length=40)),
                ('pages', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='work_space.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
