# Generated by Django 4.2.3 on 2023-11-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0009_remove_article_is_electronic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='has_author',
        ),
    ]
