# Generated by Django 4.2.3 on 2023-11-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0010_remove_website_has_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='multiple_authors',
        ),
        migrations.CreateModel(
            name='Endnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apa_text', models.CharField(max_length=50)),
                ('mla_text', models.CharField(max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endnote', to='bookshelf.source')),
            ],
        ),
    ]
