# Generated by Django 4.2.3 on 2023-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0010_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='journal_electronic',
            new_name='is_electronic',
        ),
        migrations.AddField(
            model_name='article',
            name='journal_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='volume_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
