# Generated by Django 4.2.3 on 2023-11-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_rename_journal_electronic_article_is_electronic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.book')),
                ('chapter_title', models.CharField(max_length=50)),
                ('chapter_author', models.CharField(max_length=70)),
                ('edition', models.IntegerField(blank=True)),
                ('pages', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('bookshelf.book',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=70)),
                ('has_author', models.BooleanField(default=False)),
                ('page_title', models.CharField(max_length=50)),
                ('website_title', models.CharField(max_length=50)),
                ('page_url', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
