# Generated by Django 4.2.3 on 2023-11-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_remove_source_multiple_authors_endnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endnote',
            old_name='apa_text',
            new_name='apa',
        ),
        migrations.RenameField(
            model_name='endnote',
            old_name='mla_text',
            new_name='mla',
        ),
    ]
