# Generated by Django 4.2.3 on 2023-11-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_rename_apa_text_endnote_apa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='journal_number',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='volume_number',
            new_name='volume',
        ),
    ]
