# Generated by Django 4.2.3 on 2023-11-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bookshelf', '0012_chapter_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
        migrations.AddField(
            model_name='quote',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='object_id',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
    ]
