# Generated by Django 4.2.3 on 2023-11-07 14:37

import bookshelf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_space', '0002_comment'),
        ('bookshelf', '0013_remove_quote_book_quote_content_type_quote_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=70)),
                ('multiple_authors', models.BooleanField(default=False)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('file', models.FileField(blank=True, upload_to=bookshelf.models.saving_path)),
                ('link', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.RemoveField(
            model_name='website',
            name='author',
        ),
        migrations.RemoveField(
            model_name='website',
            name='id',
        ),
        migrations.RemoveField(
            model_name='website',
            name='page_title',
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='work_space',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='work_space.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='source_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='source_ptr',
            field=models.OneToOneField(auto_created=True, default=7, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='source_ptr',
            field=models.OneToOneField(auto_created=True, default=20, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.source'),
            preserve_default=False,
        ),
    ]
