# Generated by Django 4.2.3 on 2023-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0014_alter_endnote_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='in_text_citation',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
    ]
