# Generated by Django 4.2.3 on 2023-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0016_remove_quote_in_text_citation_quote_apa_citation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='apa_citation',
            new_name='apa',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='mla_citation',
            new_name='mla',
        ),
    ]
