# Generated by Django 4.2.3 on 2023-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0017_rename_apa_citation_quote_apa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='edition',
            field=models.CharField(max_length=10),
        ),
    ]
