# Generated by Django 4.2.3 on 2023-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0018_alter_article_issue_alter_article_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='publishing_house',
            field=models.CharField(default='penguin', max_length=20),
            preserve_default=False,
        ),
    ]
