# Generated by Django 4.2.3 on 2023-11-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0019_chapter_publishing_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_author',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_title',
            new_name='book_title',
        ),
    ]
