# Generated by Django 4.2.3 on 2023-11-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0020_rename_chapter_author_chapter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='publishing_house',
        ),
    ]
