# Generated by Django 4.2.3 on 2023-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0021_remove_chapter_publishing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='publishing_house',
            field=models.CharField(default='Penguin Books', max_length=20),
            preserve_default=False,
        ),
    ]
