# Generated by Django 4.2.3 on 2023-11-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0023_alter_website_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Webpage',
        ),
    ]
