# Generated by Django 4.2.3 on 2024-01-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
