# Generated by Django 4.2.3 on 2023-11-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work_space.workspace'),
        ),
    ]
