# Generated by Django 4.2.3 on 2023-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
