# Generated by Django 4.2.3 on 2023-12-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='is_archived',
            new_name='archived',
        ),
    ]
