# Generated by Django 4.2.3 on 2023-12-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_rename_is_archived_workspace_archived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
