# Generated by Django 4.2.3 on 2023-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_alter_comment_work_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='citation_style',
            field=models.CharField(default='APA & MLA', max_length=10),
        ),
    ]
