# Generated by Django 4.2.3 on 2023-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_workspace_citation_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(default='ivite', max_length=15),
        ),
    ]
