# Generated by Django 4.2.3 on 2024-02-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_remove_workspace_share_sources'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
