# Generated by Django 4.2.3 on 2023-12-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='citation_style',
        ),
    ]
