# Generated by Django 4.2.3 on 2024-02-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0004_delete_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='guests',
            new_name='members',
        ),
    ]
