# Generated by Django 4.2.3 on 2023-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0006_alter_workspace_guests_alter_workspace_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='share_sources',
            field=models.BooleanField(default=False),
        ),
    ]
